mongodb:
  max:
    pool:
      size: 300

spring:
  servlet:
  multipart:
    max-file-size: 3MB
  application:
    name: Order-service
  data:
    mongodb:
      database:  goreit
      authentication-database: admin
      host: localhost
      port: 27017
      password: root
      username: root

#  cloud:
#    kubernetes:
#      discovery:
#        all-namespaces: true


server:
  port: 8081

#ribbon:
#  http:
#    client:
#      enabled: true

