mongodb:
  max:
    pool:
      size: 300

spring:
  servlet:
  multipart:
    enabled: true
    max-file-size: 20MB
  application:
    name: Order-service
  data:
    mongodb:
      database:  goreit
      authentication-database: admin
      host: localhost
      port: 27017
      password: root
      username: root
  datasource:
    schema-name: camunda
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

server:
  port: 8081

camunda.bpm:
  database:
    type: postgres
  admin-user:
    id: demo
    password: admin
    firstName: admin
  filter:
    create: All tasks



#      cloud:
#    kubernetes:
#      discovery:
#        all-namespaces: true


#ribbon:
#  http:
#    client:
#      enabled: true
